// <auto-generated />
using System;
using CoreBPM.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreBPM.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429192500_AddDmnTables")]
    partial class AddDmnTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<DateTimeOffset>("LastPasswordChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_password_change_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_auth_accounts");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_accounts_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_accounts_username");

                    b.ToTable("auth_accounts", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auth_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_roles_name");

                    b.ToTable("auth_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Системный администратор",
                            IsSystem = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Обычный пользователь",
                            IsSystem = true,
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Гость",
                            IsSystem = true,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_info");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_auth_sessions_account_id");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_user_roles");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_auth_user_roles_account_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_auth_user_roles_role_id");

                    b.ToTable("auth_user_roles", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmElementConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("element_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bpm_element_configs");

                    b.HasIndex("ProcessId", "ElementId")
                        .IsUnique()
                        .HasDatabaseName("ix_bpm_element_configs_process_id_element_id");

                    b.ToTable("bpm_element_configs", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bpm_processes");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_bpm_processes_created_by_user_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_bpm_processes_organization_id");

                    b.ToTable("bpm_processes", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmProcessVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("default_value");

                    b.Property<bool>("IsInput")
                        .HasColumnType("boolean")
                        .HasColumnName("is_input");

                    b.Property<bool>("IsKeyVariable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_key_variable");

                    b.Property<bool>("IsOutput")
                        .HasColumnType("boolean")
                        .HasColumnName("is_output");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VariableType")
                        .HasColumnType("integer")
                        .HasColumnName("variable_type");

                    b.HasKey("Id")
                        .HasName("pk_bpm_process_variables");

                    b.HasIndex("ProcessId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_bpm_process_variables_process_id_name");

                    b.ToTable("bpm_process_variables", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmProcessVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DiagramXml")
                        .HasColumnType("text")
                        .HasColumnName("diagram_xml");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_bpm_process_versions");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_bpm_process_versions_process_id");

                    b.HasIndex("ProcessId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_bpm_process_versions_process_id_version_number");

                    b.ToTable("bpm_process_versions", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmRaciEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<int>("RaciType")
                        .HasColumnType("integer")
                        .HasColumnName("raci_type");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("role");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_bpm_raci_entries");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_bpm_raci_entries_process_id");

                    b.ToTable("bpm_raci_entries", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("path");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_org_departments");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_org_departments_parent_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_org_departments_organization_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.ToTable("org_departments", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgDepartmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("Id")
                        .HasName("pk_org_department_history");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_org_department_history_changed_by_user_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_org_department_history_department_id");

                    b.ToTable("org_department_history", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_org_employees");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_org_employees_organization_id");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_org_employees_user_id_organization_id");

                    b.ToTable("org_employees", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_org_organizations");

                    b.HasIndex("IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("ix_org_organizations_is_primary")
                        .HasFilter("is_primary = true");

                    b.ToTable("org_organizations", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("PlannedHeadcount")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("planned_headcount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_org_positions");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_org_positions_department_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_org_positions_organization_id_code")
                        .HasFilter("code IS NOT NULL AND is_deleted = false");

                    b.ToTable("org_positions", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPositionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("rate");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_org_position_assignments");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_org_position_assignments_department_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_org_position_assignments_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_org_position_assignments_user_id");

                    b.HasIndex("PositionId", "EndDate")
                        .HasDatabaseName("ix_org_position_assignments_position_id_end_date");

                    b.ToTable("org_position_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_org_position_assignments_dates", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_org_position_assignments_rate", "rate IN (0.25, 0.50, 0.75, 1.00)");
                        });
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPositionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("Id")
                        .HasName("pk_org_position_attachments");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_org_position_attachments_position_id");

                    b.ToTable("org_position_attachments", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPositionRoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_org_position_role_mappings");

                    b.HasIndex("PositionId", "RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_org_position_role_mappings_position_id_role_name");

                    b.ToTable("org_position_role_mappings", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("work_email");

                    b.HasKey("Id")
                        .HasName("pk_org_users");

                    b.HasIndex("WorkEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_org_users_work_email");

                    b.ToTable("org_users", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Annotation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("annotation");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("column_id");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uuid")
                        .HasColumnName("row_id");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_rules_dmn_cells");

                    b.HasIndex("ColumnId")
                        .HasDatabaseName("ix_rules_dmn_cells_column_id");

                    b.HasIndex("RowId", "ColumnId")
                        .IsUnique()
                        .HasDatabaseName("ix_rules_dmn_cells_row_id_column_id");

                    b.ToTable("rules_dmn_cells", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ColumnKind")
                        .HasColumnType("integer")
                        .HasColumnName("column_kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer")
                        .HasColumnName("value_type");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_rules_dmn_columns");

                    b.HasIndex("VersionId", "Order")
                        .HasDatabaseName("ix_rules_dmn_columns_version_id_order");

                    b.ToTable("rules_dmn_columns", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_rules_dmn_rows");

                    b.HasIndex("VersionId", "Order")
                        .HasDatabaseName("ix_rules_dmn_rows_version_id_order");

                    b.ToTable("rules_dmn_rows", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("HitPolicy")
                        .HasColumnType("integer")
                        .HasColumnName("hit_policy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_rules_dmn_tables");

                    b.ToTable("rules_dmn_tables", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnTableVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_rules_dmn_table_versions");

                    b.HasIndex("TableId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_rules_dmn_table_versions_table_id_version_number");

                    b.ToTable("rules_dmn_table_versions", (string)null);
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthAccount", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgUser", "User")
                        .WithOne("Account")
                        .HasForeignKey("CoreBPM.Server.Domain.Auth.AuthAccount", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_accounts_org_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthSession", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Auth.AuthAccount", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_auth_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthUserRole", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Auth.AuthAccount", "Account")
                        .WithMany("UserRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_auth_accounts_account_id");

                    b.HasOne("CoreBPM.Server.Domain.Auth.AuthRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_auth_roles_role_id");

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmElementConfig", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Bpm.BpmProcess", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bpm_element_configs_bpm_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmProcessVariable", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Bpm.BpmProcess", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bpm_process_variables_bpm_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmProcessVersion", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Bpm.BpmProcess", "Process")
                        .WithMany("Versions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bpm_process_versions_bpm_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmRaciEntry", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Bpm.BpmProcess", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bpm_raci_entries_bpm_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgDepartment", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgOrganization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_departments_org_organizations_organization_id");

                    b.HasOne("CoreBPM.Server.Domain.Org.OrgDepartment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_org_departments_org_departments_parent_id");

                    b.Navigation("Organization");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgDepartmentHistory", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_org_department_history_org_users_changed_by_user_id");

                    b.HasOne("CoreBPM.Server.Domain.Org.OrgDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_department_history_org_departments_department_id");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgEmployee", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgOrganization", "Organization")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_employees_org_organizations_organization_id");

                    b.HasOne("CoreBPM.Server.Domain.Org.OrgUser", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_employees_org_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPosition", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_org_positions_org_departments_department_id");

                    b.HasOne("CoreBPM.Server.Domain.Org.OrgOrganization", "Organization")
                        .WithMany("Positions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_positions_org_organizations_organization_id");

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPositionAssignment", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_org_position_assignments_org_departments_department_id");

                    b.HasOne("CoreBPM.Server.Domain.Org.OrgOrganization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_position_assignments_org_organizations_organization_id");

                    b.HasOne("CoreBPM.Server.Domain.Org.OrgPosition", "Position")
                        .WithMany("Assignments")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_position_assignments_org_positions_position_id");

                    b.HasOne("CoreBPM.Server.Domain.Org.OrgUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_org_position_assignments_org_users_user_id");

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPositionAttachment", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgPosition", "Position")
                        .WithMany("Attachments")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_position_attachments_org_positions_position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPositionRoleMapping", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Org.OrgPosition", "Position")
                        .WithMany("RoleMappings")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_position_role_mappings_org_positions_position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnCell", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Rules.DmnColumn", "Column")
                        .WithMany("Cells")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rules_dmn_cells_rules_dmn_columns_column_id");

                    b.HasOne("CoreBPM.Server.Domain.Rules.DmnRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rules_dmn_cells_rules_dmn_rows_row_id");

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnColumn", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Rules.DmnTableVersion", "Version")
                        .WithMany("Columns")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rules_dmn_columns_rules_dmn_table_versions_version_id");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnRow", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Rules.DmnTableVersion", "Version")
                        .WithMany("Rows")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rules_dmn_rows_rules_dmn_table_versions_version_id");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnTableVersion", b =>
                {
                    b.HasOne("CoreBPM.Server.Domain.Rules.DmnTable", "Table")
                        .WithMany("Versions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rules_dmn_table_versions_rules_dmn_tables_table_id");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthAccount", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Auth.AuthRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Bpm.BpmProcess", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgDepartment", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgOrganization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgPosition", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("RoleMappings");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Org.OrgUser", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnColumn", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnTable", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CoreBPM.Server.Domain.Rules.DmnTableVersion", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
